### ISSUE TITLE
Should all ships be a derived class of Ship

### ISSUE THREAD

**Issue by bgklug** [mabilan/CS372-Proj1#2]
It would be easier and cleaner if each ship is its own class that has a unique constructor that sets the desired parameters.

The alternative would be passing the name and size to the constructor.

**Comment by mabilan** [comment]
I agree that each ship could easily be a class derived from ship. So, we need to know exactly what things a ship needs to know about itself. As a base, I think these are the only things that matter:
- Name
- Identifier (single-character field)
- A "print" function that puts the ID into an output stream (for printing)
- Size (e.g. how many spaces it occupies)

We'll probably need to iron out how we want to implement our ship/board design. As-is, I see we've added a position struct to ships, and I don't think it's necessary if we are ALSO using a board to manage ship (otherwise ships depend on boards and vice versa and it makes this less modular/portable).

**Comment by mabilan** [comment]
Per discussion:
- Ship will be a base class. All specific ships will derive from base ship.
- Ships do not need to know their own location: another object that stores ships (e.g. gameboard, fleet, whatever) will store ship locations.
- Ships need to know whether or not they have been sunk.
